### ISSUE TITLE
[ToDo] Improve Advanced Search

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#78]
- [x] Add pseudo/total mod suggestions (life + strength = total life).
- [ ] (Maybe) Add multi group pseudo mods (jewels for example)
- [x] Add ilvl field
- [x] Fix map search
