### ISSUE TITLE
ToDo Checklist (minor issues)

### ISSUE THREAD

**Issue by Eruyome** [PoE-TradeMacro/POE-TradeMacro#85]
- [x] Advanced Search not working for some unique jewels
- [x] Test gzip compression. (WinHTTP)
- [x] Rework badly implemented league parsing
